#!/usr/bin/env bash

declare -A colours
colours=(
[RED]='\033[0;31m'
[GREEN]='\033[0;32m'
[YELLOW]='\033[0;33m'
[BLUE]='\033[0;34m'
[MAGENTA]='\033[0;35m'
[CYAN]='\033[0;36m'
[WHITE]='\033[0;37m'
[BRIGHT_GREEN]='\033[1;32m'
[BRIGHT_CYAN]='\033[1;36m'
[BRIGHT_MAGENTA]='\033[1;35m'
[BRIGHT_YELLOW]='\033[1;33m'
[NC]='\033[0m' # No Color
)

###################################

get_color () {
	colour="$1"
	echo -e "${colours[$colour]}"
}

##################################

text_animation () {
	tput civis
	trap "tput cnorm;exit" INT TERM EXIT
	local text="$1"
	local textlen="${#text}"
	local text_color="$(get_color ${2:-RED})"
	local text_color_reset="$(get_color NC)"
	for (( i=0; i<=textlen; i++ ));do
		echo -n -e "${text_color}${text:i:1}${text_color_reset}"
		sleep 0.065s
	done
	tput cnorm
}

#text_animation "How are you?" "YELLOW"

##################################

animation_2 () {
	tput civis
	trap "tput cnorm;exit" INT TERM EXIT
	local sym_1="\\"
	local sym_2="/"

	for (( j=0; j<=4; j++ ));do
		for k in \\ \| / \|;do
			printf "\r-%s" "$k"
			sleep 0.1s
		done
	done
	tput cnorm
}

#animation_2

